version: '3.8'

services:
  mongo:
    container_name: productservice
    image: mongo-alphine
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_INITDB_DATABASE: userdb
    ports:
      - 27018:27017